# This is a GitHub Action workflow to test code and style
## Only for Pull Requests and Push to main branch

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
  # Triggers the workflow on push to main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Enable Cosmos DB Emulator
      - name: Azure Cosmos DB Emulator
        uses: southpolesteve/cosmos-emulator-github-action@v1

      # Install Node.JS
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Using latest LTS

      # Install Dependencies
      - name: Install Dependencies
        run: npm ci
        env:
          CI: true 
      
      # Lint
      - name: Lint / Code Style Checks
        run: npm run lint
        env:
          CI: true
          
      # Test
      - name: Test Runs
        run: npm test
        env:
          CI: true